-- SQL Script for Dental Clinic System

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

CREATE DATABASE IF NOT EXISTS `ClinicaDentalEsdent`;
USE `ClinicaDentalEsdent`;

CREATE TABLE `pacientes` (
    `idPaciente`                                int(11)                         NOT NULL COMMENT 'ID del paciente',
    `Nombre`                                    varchar(100)                DEFAULT NULL COMMENT 'Nombres del paciente',
    `Apellido`                                  varchar(100)                DEFAULT NULL COMMENT 'Apellidos del paciente',
    `Fecha_nacimiento`                          varchar(100)                        DEFAULT NULL COMMENT 'Fecha de nacimiento del paciente',
    `Edad`                                      int(11)                     DEFAULT NULL COMMENT 'Edad del paciente',
    `Direccion`                                 varchar(255)                DEFAULT NULL COMMENT 'Dirección del paciente',
    `Telefono`                                  varchar(20)                 DEFAULT NULL COMMENT 'Teléfono del paciente',
    `Correo`                                    varchar(100)                DEFAULT NULL COMMENT 'Correo electrónico del paciente',
    `Estado_civil`                              varchar(50)                 DEFAULT NULL COMMENT 'Estado civil del paciente',
    `Ocupacion`                                 varchar(100)                DEFAULT NULL COMMENT 'Ocupación del paciente',
    `Recomendacion`                             varchar(100)                DEFAULT NULL COMMENT 'Quién recomendó al paciente',
    `Genero`                                    enum('Masculino',   
                                                     'Femenino',    
                                                     'Otro')                DEFAULT NULL COMMENT 'Género del paciente',
    `Esta_embarazada`                           enum('Si','No')             DEFAULT NULL COMMENT 'Si está embarazada',
    `Meses_de_gestacion`                        tinyint(4)                  DEFAULT NULL COMMENT 'Meses de gestación (si está embarazada)',
    `Motivo_consulta`                           text                        DEFAULT NULL COMMENT 'Motivo de la consulta',
    `Ultima_visita_odontologo`                  varchar(255)                DEFAULT NULL COMMENT 'Última visita al odontólogo',
    `Cepillo_dientes_al_dia`                    tinyint(4)                  DEFAULT NULL COMMENT 'Frecuencia con la que se cepilla los dientes al día',
    `Sangrado_encias`                           enum('Si','No','Aveces')    DEFAULT NULL COMMENT 'Si tiene sangrado de encías',
    `Aprieta_dientes`                           enum('Si','No')             DEFAULT NULL COMMENT 'Si aprieta los dientes',
    `Durante_dia_o_noche`                       enum('día',
                                                     'noche',
                                                     'Ambos')               DEFAULT NULL COMMENT 'Si aprieta los dientes en el día o en la noche',
    `Ha_realizado_cirugia_bucal`                enum('Si','No')             DEFAULT NULL COMMENT 'Si se ha realizado alguna cirugía',
    `Que_operacion_bucal`                       varchar(255)                DEFAULT NULL COMMENT 'Medicamentos a los que es alérgico',
    `Dificultad_abrir_boca`                     enum('Si','No')             DEFAULT NULL COMMENT 'Si tiene dificultad para abrir la boca',
    `Tiene_brackets`                            enum('Si','No')             DEFAULT NULL COMMENT 'Si tiene brackets',
    `Toma_medicamentos`                         enum('Si','No')             DEFAULT NULL COMMENT 'Toma medicamentos el paciente',
    `Que_medicamento`                           varchar(255)                DEFAULT NULL COMMENT 'Medicamentos que está tomando actualmente',
    `Alergico_a_medicamento`                    enum('Si','No')             DEFAULT NULL COMMENT 'Es alergico a un medicamento',
    `Medicamento_que_es_alergico`               varchar(255)                DEFAULT NULL COMMENT 'Medicamentos a los que es alérgico',
    `Mala_experiencia_con_anestesicos`          enum('Si','No')             DEFAULT NULL COMMENT 'Ha tenido mala experiencia con anestesicos',
    `Cual_anestesico`                           varchar(255)                DEFAULT NULL COMMENT 'Con cuales anestesicos',
    `Lo_han_operado`                            enum('Si','No')             DEFAULT NULL COMMENT 'Lo han operado',  
    `Que_operacion_le_han_hecho`                varchar(255)                DEFAULT NULL COMMENT 'Que operación le han realizado',
    `Lo_han_operado_corazon`                    enum('Si','No')             DEFAULT NULL COMMENT 'Lo han operado del corazón',
    `Tiene_marcapasos_corazon`                  varchar(255)                DEFAULT NULL COMMENT 'Tiene algún marcapasos en el corazón',
    `Toma_anticoagulante`                       enum('Si','No')             DEFAULT NULL COMMENT 'Toma algún anticoagulante',
    `Cual_anticoagulante_toma`                  varchar(255)                DEFAULT NULL COMMENT 'Que anticoagulante toma',
    `Tiene_tratamiento_antidepresivo`           enum('Si','No')             DEFAULT NULL COMMENT 'Está en tratamiento antidepresivo',
    `Que_Tratamiento_Antidepresivo`             varchar(255)                DEFAULT NULL COMMENT 'Qué tratamiento antidepresivo toma',
    `Artritis_reumatoide`                       enum('Si','No')             DEFAULT NULL COMMENT 'Padece de artritis reumatoide',
    `Padece_osteoporosis`                       enum('Si','No')             DEFAULT NULL COMMENT 'Padece de osteoporosis',
    `Tiene_diabetes`                            enum('Si','No')             DEFAULT NULL COMMENT 'Tiene diabetes',
    `Que_valores_diabetes_maneja`               varchar(255)                DEFAULT NULL COMMENT 'Qué valores maneja',
    `Es_hipertenso`                             enum('Si','No')             DEFAULT NULL COMMENT 'Es hipertenso',
    `Valores_hipertenso_maneja`                 varchar(255)                DEFAULT NULL COMMENT 'Qué valores maneja',
    `Le_han_realizado_transfusion_sanguinea`    enum('Si','No')             DEFAULT NULL COMMENT 'Le han realizado transfusiones sanguíneas',
    `Sangra_al_cortarse`                        enum('Si','No')             DEFAULT NULL COMMENT 'Sangra mucho al cortarse',
    `Ha_tenido_infarto_corazon`                 enum('Si','No')             DEFAULT NULL COMMENT 'Ha tenido infarto en el corazón',
    `Tiene_protesis_corazon`                    enum('Si','No')             DEFAULT NULL COMMENT 'Tiene prótesis en el corazón',
    `Toma_acido_zoledronico`                    enum('Si','No')             DEFAULT NULL COMMENT 'Toma ácido zoledrónico',
    `Toma_fosamax_alendronato`                  enum('Si','No')             DEFAULT NULL COMMENT 'Toma Fosamax (Alendronato)',
    `Toma_ibandronato_boniva`                   enum('Si','No')             DEFAULT NULL COMMENT 'Toma Ibandronato (Boniva)',
    `Toma_actonel_risedronato`                  enum('Si','No')             DEFAULT NULL COMMENT 'Toma Actonel (Risedronato)',
    `Enfermedades_corazon`                      enum('Si','No')             DEFAULT NULL COMMENT 'Tiene enfermedades del corazón',
    `Enfermedades_pulmonares`                   enum('Si','No')             DEFAULT NULL COMMENT 'Tiene enfermedades pulmonares',
    `Insuficiencia_renal`                       enum('Si','No')             DEFAULT NULL COMMENT 'Tiene insuficiencia renal',
    `Gastritis`                                 enum('Si','No')             DEFAULT NULL COMMENT 'Tiene gastritis',
    `Epilepsia`                                 enum('Si','No')             DEFAULT NULL COMMENT 'Tiene epilepsia',
    `Diabetes`                                  enum('Si','No')             DEFAULT NULL COMMENT 'Tiene diabetes',
    `Paralisis`                                 enum('Si','No')             DEFAULT NULL COMMENT 'Tiene parálisis',
    `vih_sida`                                  enum('Si','No')             DEFAULT NULL COMMENT 'Tiene VIH/SIDA',
    `Tuberculosis`                              enum('Si','No')             DEFAULT NULL COMMENT 'Tiene tuberculosis',
    `Hemofilia`                                 enum('Si','No')             DEFAULT NULL COMMENT 'Tiene hemofilia',
    `Hepatitis`                                 enum('Si','No')             DEFAULT NULL COMMENT 'Tiene hepatitis',
    `Anemia`                                    enum('Si','No')             DEFAULT NULL COMMENT 'Tiene anemia',
    `Presion_alta`                              enum('Si','No')             DEFAULT NULL COMMENT 'Tiene presión alta',
    `Presion_baja`                              enum('Si','No')             DEFAULT NULL COMMENT 'Tiene presión baja',
    `Asma`                                      enum('Si','No')             DEFAULT NULL COMMENT 'Tiene asma',
    `Artritis`                                  enum('Si','No')             DEFAULT NULL COMMENT 'Tiene artritis',
    `Tiroides`                                  enum('Si','No')             DEFAULT NULL COMMENT 'Tiene problemas de tiroides',
    `Cancer`                                    enum('Si','No')             DEFAULT NULL COMMENT 'Tiene cáncer',
    `Familiar_padecido_enfermedades`            enum('Si','No')             DEFAULT NULL COMMENT 'Algún familiar ha padecido de alguna de las enfermedades anteriores',
    `Enfermedades_padecidas`                    text                        DEFAULT NULL COMMENT 'Enfermedades que han padecido',
    `Quien_padecio`                             text                        DEFAULT NULL COMMENT 'Quiénes han padecido las enfermedades',
    `Fuma`                                      enum('Si','No')             DEFAULT NULL COMMENT 'Fuma',
    `Cuantos_cigarros_al_dia_fuma`              int(11)                     DEFAULT NULL COMMENT 'Cuántos cigarros al día fuma',
    `Consume_drogas`                            enum('Si','No')             DEFAULT NULL COMMENT 'Consume droga',
    `Drogas_consumiendo`                        text                        DEFAULT NULL COMMENT 'Drogas a las que consume',
    `Consume_alcohol`                           enum('Si','No')             DEFAULT NULL COMMENT 'Consume alcohol',
    `Firma`                                     blob                        DEFAULT NULL COMMENT 'Firma del paciente',
    `Foto_paciente`                             LONGBLOB                    DEFAULT NULL COMMENT 'Foto del paciente',
    `fecha_registro`                              datetime DEFAULT current_timestamp()   COMMENT 'Fecha y hora en la que se registró el paciente',
    PRIMARY KEY (`idPaciente`)                                                           
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Tabla que almacena toda la información relevante de los pacientes para la clínica dental.';
